
---
title: "Research Software Engineering Master Curriculum"
format:
    beamer:
        keep-tex: true
        aspectratio: 169
        navigation: horizontal
        pdf-engine: pdflatex
        include-in-header:
            - beamer-header.tex
        latex-auto-install: true
        section-titles: true
        mermaid: true
---

# Research Software RSE Master Curriculum Project

-  software-based research plays an increasingly central role
-  qualified research software engineers (RSEs) are rare (mostly Quereinsteiger)
-  delineation of the emerging field is challenging

# First Issues and Current Answers

1. Is RSE a CS study program? Yes, but not only
2. What is the BA requirement (audience)? CS or MNT depending on profile
3. Is RSE a recomposition of existing lectures? yes, but only partially
4. What is the intended job profile (if any)? Academia and research institutes primarily
5. Is the Curriculum one idea or a set of ideas? At least two ideas are dominating


3-4 Gruppen

1. Welche Informatikvertiefungen sollten drin sein
2. Gelingensfaktoren vs. Fail Cases?
3. Art der Einführung, beste Vorgehensweise
4. Karrierewege für Track 1, und welche Anforderungen werden gestellt



nochmal die World Cafe Themen aus dem Zoom Chat:
1. (R)SE-Modulreihe (Module und Reihenfolge)
2. Karriereprofile (mit Anforderungen) -> Vertiefungsmodule (Pflicht & Wahlpflicht) im CS-Track
3. Erfolgsfaktoren/ Gelingensbedingungen und Risiken für die Einführung (politisch-strategisch)
4. mögliche Modelle/Methoden zur Einführung an Hochschulen