sources:
  curricula:
    - name: Computing Curricula 2020
      link: https://dl.acm.org/doi/book/10.1145/3467967
  courses:
    - name: UP Grundlagen der Programmierung
      link: "https://puls.uni-potsdam.de/qisserver/pages/cs/sys/portal/hisinoneIframePage.faces?id=qis_MKSuchen_0&navigationPosition=up_modulbeschreibung%2Cqis_MKSuchen&recordRequest=true"
    - name: UP Praxis der Programmierung
      link: "https://puls.uni-potsdam.de/qisserver/pages/cs/sys/portal/hisinoneIframePage.faces?id=qis_MKSuchen_0&navigationPosition=up_modulbeschreibung%2Cqis_MKSuchen&recordRequest=true"
    - name: Python for Psychologists
      link: "https://peerherholz.github.io/Python_for_Psychologists_Winter2021/index.html"
  programs:
    - name: UP Computational Science Master
      link: "https://www.uni-potsdam.de/de/studium/konkret/rechtsgrundlagen/studienordnungen/informatik"
