sources:
  curricula:
    - name: Computing Curricula 2020
      link: "https://dl.acm.org/doi/book/10.1145/3467967"
  courses:
    - name: Grundlagen der Programmierung
      link: "https://www.uni-potsdam.de/fileadmin/projects/ambek/Amtliche_Bekanntmachungen/2024/Ausgabe_20/ambek-2024-20-873-879.pdf"
    - name: Python for Psychologists
      link: "https://peerherholz.github.io/Python_for_Psychologists_Winter2021/index.html"
    - name: Grundlagen der Informatik
      link: "https://ekvv.uni-bielefeld.de/sinfo/publ/modul/50702407"
    - name: Grundlagen der Programmierung
      link: "https://www2.uni-wuerzburg.de/mhb/MHB1-de-82-079-H-2025.pdf"
    - name: Programmierung
      link: "https://online.rwth-aachen.de/RWTHonline/pl/ui/$ctx;design=pl;header=max;lang=de/wbModhbReport.downloadPublicMHBVersion?pOrgNr=14194&pStpStpNr=1970&pDocNr=14085952"
    - name: Programmierung 1
      link: "https://www.uni-saarland.de/fileadmin/upload/studium/angebot/mhb_ba/2025/MHB_BA_Inform.pdf"
  programs:
    - name: UP Informatik/Computational Science Bachelor
      link: "https://www.uni-potsdam.de/de/studium/studienangebot/bachelor/ein-fach-bachelor/informatikcomputational-science-ein-fach-bachelor"
    - name: JMUW Informatik Bachelor
      link: "https://www.informatik.uni-wuerzburg.de/studium/studiengaenge/bachelor-informatik/"
    - name: RWTH Informatik Bachelor
      link: "https://www.rwth-aachen.de/cms/root/studium/vor-dem-studium/studiengaenge/liste-aktuelle-studiengaenge/studiengangbeschreibung/~bnzs/informatik-b-sc-/"
    - name: UdS Informatik Bachelor
      link: "https://www.uni-saarland.de/studium/angebot/bachelor/informatik.html"
