## Complexity Theory

### Introduction

This module covers advanced complexity theory.

### Contents

The module includes the following topics:

- Deterministic, non-deterministic, probabilistic and parallel computational models
- Complexity classes; reductions
- Complexity of approximation problems
- Selection of advanced topics such as interactive proofs, derandomisation, circuit complexity, communication complexity, parametric complexity
- Properties of NP-complete sets, autoreducibility, polynomial time hierarchy
- complexity of probabilistic algorithms.

### Learning Objectives

Students are able to analyse the correctness, security and complexity of processes.
Students will be able to classify algorithmic problems according to their complexity.
Students will be able to analyse the relationship between different complexity classes.

### Examination Methods

- Either a 90-minute written exam.
- Or a 20-30 minute oral examination.

### Sources & Implementations:

#### Courses

- [Komplexitätstheorie](https://online.rwth-aachen.de/RWTHonline/pl/ui/$ctx;design=pl;header=max;lang=de/wbModhbReport.downloadPublicMHBVersion?pOrgNr=14194&pStpStpNr=1975&pDocNr=14085970)

- [Sicherheit, Information und Komplexität](https://www.uni-potsdam.de/fileadmin/projects/ambek/Amtliche_Bekanntmachungen/2024/Ausgabe_20/ambek-2024-20-885-891.pdf)

- [Komplexitätstheorie II](https://www2.uni-wuerzburg.de/mhb/MHB1-de-88-079-H-2025.pdf)

#### Programs

- [UP Computational Science Master](https://www.uni-potsdam.de/de/studium/studienangebot/master/computational-science)

- [RWTH Informatik Master](https://www.rwth-aachen.de/go/id/bcfg)

- [JMUW Informatik Master](https://www.informatik.uni-wuerzburg.de/studium/studiengaenge/master-informatik/)

::: {.content-visible when-format="html"}

::: {#refs}
:::

:::
