## Design of Efficient Algorithms

### Introduction

This module deals with efficient algorithms, optimisation, and approximation algorithms.

### Contents

Architecture and implementation of formal systems for the design of efficient algorithms, correctness-preserving optimisation, programme verification and synthesis.
Design and analysis of approximation algorithms.

### Learning Objectives

Students will be familiar with and understand basic techniques of formal programme development and its implementation.
Students will be able to anticipate efficiency problems when designing algorithms and respond accordingly.
Students will write better programmes that are highly optimised in their runtime-critical areas.
Students will be able to analyse simple approximation methods in terms of their quality. They understand basic design techniques such as greedy, local search, scaling and methods based on linear programming and can also apply these to new problems.

### Examination Methods

- Either a 90-minute written exam.
- Or a 30 minute oral examination.

### Sources & Implementations:

#### Courses

- [Entwurf effizienter Algorithmen](https://www.uni-potsdam.de/fileadmin/projects/ambek/Amtliche_Bekanntmachungen/2024/Ausgabe_20/ambek-2024-20-885-891.pdf)

- [Analyse von Algorithmen](https://online.rwth-aachen.de/RWTHonline/pl/ui/$ctx;design=pl;header=max;lang=de/wbModhbReport.downloadPublicMHBVersion?pOrgNr=14194&pStpStpNr=1975&pDocNr=14085970)

- [Approximationsalgorithmen](https://www2.uni-wuerzburg.de/mhb/MHB1-de-88-079-H-2025.pdf)

#### Programs

- [UP Computational Science Master](https://www.uni-potsdam.de/de/studium/studienangebot/master/computational-science)

- [RWTH Informatik Master](https://www.rwth-aachen.de/go/id/bcfg)

- [JMUW Informatik Master](https://www.informatik.uni-wuerzburg.de/studium/studiengaenge/master-informatik/)

::: {.content-visible when-format="html"}

::: {#refs}
:::

:::
