## IT-Security and Cryptography

### Introduction

This module deals with IT-security and cryptography.

### Contents

The course offers a broad overview of concepts and technologies relevant to IT security:
- Theoretical aspects: security in information theory and computability, introduction to cryptography (historical and modern ciphers, hash functions, pseudo-random number generators, message authentication codes, public-key cryptography)
- Network security: security of protocols and TCP/IP, public key infrastructure, user authentication, Kerberos, IPsec, TLS protocol, SSH,
DNS Security, Email Security, and Phishing Attacks.
- Software security: security vulnerabilities, common programming errors and techniques for exploiting them, reverse engineering and obfuscation, malware and anti-malware
- Platform security: access control models, security policies, operating system security, virtualisation, security mechanisms with hardware support
- Methods for secure and reliable transmission and processing of information, error-correcting coding methods
- Fundamentals of cryptographic systems, methods for information analysis, complexity aspects, applications
- Necessary foundations of mathematics and complexity theory are introduced alongside the topics
- Private key cryptosystems, Vernam one-time pad, AES, perfect security, public key cryptosystems, RSA, Diffie-Hellman, Elgamal, Goldwasser-Micali, digital signature, challenge-response procedure, secret sharing, millionaire problem, secure circuit evaluation, homomorphic encryption
- Symmetric Encryption, Integrity protection, Asymmetric Encryption, Digital Signatures, Certificates and Public Key Infrastructures, and Authentication and Key Agreement

### Learning Objectives
Students are able to
- understand the mathematical foundations of secure and reliable information processing and their complexity-theoretical basis
- are capable of analysing thesecurity of methods
- model threats and evaluate the security of systems critically from the attacker's perspective
- understand the purpose and functioning of some security technologies and be aware of their limitations
- select and apply appropriate cryptographic primitives in different application scenarios
- select suitable security protocols for a given scenario and configure the relevant options for the cryptographic building blocks used within these protocols
- identify security requirements and adequate security mechanisms in various application domains
- identify potential weaknesses in security protocols not covered in detail during the course and propose appropriate fixes
- assess the severity of novel attacks against security protocols and cryptographic primitives

### Examination methods

- Either a written exam (90 minutes).
- Or an oral examination (30 minutes).

### Sources & Implementations:

#### Courses

- [Sicherheit, Information und Komplexität](https://www.uni-potsdam.de/fileadmin/projects/ambek/Amtliche_Bekanntmachungen/2024/Ausgabe_20/ambek-2024-20-885-891.pdf)

- [Resiliente Systeme](https://www.uni-potsdam.de/fileadmin/projects/ambek/Amtliche_Bekanntmachungen/2024/Ausgabe_20/ambek-2024-20-885-891.pdf)

- [IT-Sicherheit I](https://online.rwth-aachen.de/RWTHonline/pl/ui/$ctx;design=pl;header=max;lang=de/wbModhbReport.downloadPublicMHBVersion?pOrgNr=14194&pStpStpNr=1975&pDocNr=14085970)

- [Algorithmische Kryptographie](https://online.rwth-aachen.de/RWTHonline/pl/ui/$ctx;design=pl;header=max;lang=de/wbModhbReport.downloadPublicMHBVersion?pOrgNr=14194&pStpStpNr=1975&pDocNr=14085970)

- [Einführung in die IT-Sicherheit](https://www2.uni-wuerzburg.de/mhb/MHB1-de-88-079-H-2025.pdf)

- [Kryptographie und Datensicherheit](https://www2.uni-wuerzburg.de/mhb/MHB1-de-88-079-H-2025.pdf)

#### Programs

- [UP Computational Science Master](https://www.uni-potsdam.de/de/studium/studienangebot/master/computational-science)

- [JMUW Informatik Bachelor](https://www.informatik.uni-wuerzburg.de/studium/studiengaenge/bachelor-informatik/)

- [JMUW Informatik Master](https://www.informatik.uni-wuerzburg.de/studium/studiengaenge/master-informatik/)

- [RWTH Informatik Master](https://www.rwth-aachen.de/go/id/bcfg)

::: {.content-visible when-format="html"}

::: {#refs}
:::

:::
