## (Classical) Software Engineering II

The module covers a selection of advanced topics in the field of software engineering, for example in the areas of software quality assurance, service engineering, virtualisation, programming languages and design, and formal methods in system design. It builds on knowledge and competencies from Software Engineering I.

### Learning Objectives
Students
- have an in-depth understanding of and the ability to use various approaches to software engineering
- are familiar with the characteristics of numerous technologies and tools for specification, component-based development and quality assurance of modern software systems, as well as their application in various contexts.

### Examination Methods
* written exam (100 min)
* exercise sheets or group project

### Sources & Implementations:

#### Courses

- [Software Engineering II](https://www.uni-potsdam.de/fileadmin/projects/ambek/Amtliche_Bekanntmachungen/2024/Ausgabe_20/ambek-2024-20-873-879.pdf)

#### Programs

- [UP Informatik/Computational Science Bachelor](https://www.uni-potsdam.de/de/studium/studienangebot/bachelor/ein-fach-bachelor/informatikcomputational-science-ein-fach-bachelor)

::: {.content-visible when-format="html"}

::: {#refs}
:::

:::
