## Foundations of Computer Science

This module covers the basics of computer science and introduces the students from domain sciences to programming.

### Basic Concepts

- Introduction to computer science, basic concepts of operating systems using UNIX/Linux as an example
- From problem to algorithm: concept of an algorithm, design of algorithms, pseudocode, refinement, brute-force algorithms, models and modeling, graphs and their representation, simple algorithms on graphs, analysis of algorithms (correctness, termination, runtime)
- Implementation of algorithms (e.g., using Python)
- Programming paradigms: procedural, object-oriented, and functional programming; recursion versus iteration
- From program to process: assembly languages, assembler, compiler, interpreter, syntax and semantics of programming languages
- Limits of algorithms: computability, decidability, undecidability

### Sources & Implementations:

#### Curricula

- [Computing Curricula 2020](https://dl.acm.org/doi/book/10.1145/3467967)

#### Courses

- [Grundlagen der Programmierung](https://www.uni-potsdam.de/fileadmin/projects/ambek/Amtliche_Bekanntmachungen/2024/Ausgabe_20/ambek-2024-20-873-879.pdf)

- [Python for Psychologists](https://peerherholz.github.io/Python_for_Psychologists_Winter2021/index.html)

- [Grundlagen der Informatik](https://ekvv.uni-bielefeld.de/sinfo/publ/modul/50702407)

- [Grundlagen der Programmierung](https://www2.uni-wuerzburg.de/mhb/MHB1-de-82-079-H-2025.pdf)

- [Programmierung](https://online.rwth-aachen.de/RWTHonline/pl/ui/$ctx;design=pl;header=max;lang=de/wbModhbReport.downloadPublicMHBVersion?pOrgNr=14194&pStpStpNr=1970&pDocNr=14085952)

- [Programmierung 1](https://www.uni-saarland.de/fileadmin/upload/studium/angebot/mhb_ba/2025/MHB_BA_Inform.pdf)

#### Programs

- [UP Informatik/Computational Science Bachelor](https://www.uni-potsdam.de/de/studium/studienangebot/bachelor/ein-fach-bachelor/informatikcomputational-science-ein-fach-bachelor)

- [JMUW Informatik Bachelor](https://www.informatik.uni-wuerzburg.de/studium/studiengaenge/bachelor-informatik/)

- [RWTH Informatik Bachelor](https://www.rwth-aachen.de/cms/root/studium/vor-dem-studium/studiengaenge/liste-aktuelle-studiengaenge/studiengangbeschreibung/~bnzs/informatik-b-sc-/)

- [UdS Informatik Bachelor](https://www.uni-saarland.de/studium/angebot/bachelor/informatik.html)

::: {.content-visible when-format="html"}

::: {#refs}
:::

:::
