## RSEng Management
### Introduction

This module comprises the communication and management skills that are relevant for working in the interdisciplinary setting of RSE-professionals.

This includes but is not limited to:

- working in a team (see TEAM in [@competencies-F1000])
- teaching RSE-basics (see TEACH in [@competencies-F1000])
- project management (see PM in [@competencies-F1000])
- interaction with users and other stakeholders (see USERS in [@competencies-F1000])

The lecture covers project and team management techniques an RSE needs in everyday life and the taught methods are applied and practiced with case-studys, role-plays etc. in the exercise.

### Contents

- **research management**
    - research cycle
    - open science, FAIR, FAIR4RS
    - publication workflow: obstacles and embargoes
    - legal aspects of research data, e.g. GDPR
    - pseudonymization/anonymization methods for data privacy 
    - public databases
- **quality control**    
    - requirements engineering
    - trying goals with quality: test-driven development
    - behavior-driven development, Gherkin-Style acceptance testing
    - project folder organization
    - code review principles
- **communication and collaboration**
    - communication frameworks, e.g. AIDA, RACE, 7 C's
    - personality traits and their impact on cooperation
    - collaboration frameworks for remote work
    - realisation and benefits of pair programming and mob/ensemble programming
    - technical English writing skills: writing in issues and merge requests, code review...
    - conflict management, e.g. dealing with researchers that do not listen
    - how to address relevant stakeholders (i.e. users and SEs) with different background knowledge, experience and expectations
    - equity, diversity and inclusion principles
- **team management**
    - challenges of transient teams (that only exist for 5-15 hours)
    - effects of varying team sizes
    - management depending on project size/type
    - specialised roles in a software team
    - intercultural and interdisciplinary differences
    - team management methodologies
    - importance of shared values in a RSE team
    - dual goals: project vs. personal goal
- **time and project management**
    - goal-setting
    - project management methods, their strengths and weaknesses
    - agile (not necessarily Scrum)
    - Lean & Kanban (Small-Batch Philosophies)
    - division of tasks into sub-tasks and task-dependencies
    - iterative workflows
    - continuous delivery
    - communication with a manager/supervisor

### Piloting Classes

- [RWTH-Management and Communication in RSE Seminar](../components/rse_management/oer.qmd)

### Sources & Implementations:

#### Courses

- [RSE Leadership Course](https://events.humanitix.com/rse-leadership-course)

- [Professionelles Projektmanagement in der Praxis](https://www2.uni-wuerzburg.de/mhb/MHB1-de-88-i45-H-2024.pdf)

- [Communication Psychology](https://online.rwth-aachen.de/RWTHonline/pl/ui/$ctx;design=pl;header=max;lang=de/wbModhbReport.downloadPublicMHBVersion?pOrgNr=14194&pStpStpNr=1970&pDocNr=14085952)

- [Grundlagen des Management](https://online.rwth-aachen.de/RWTHonline/pl/ui/$ctx;design=pl;header=max;lang=de/wbModhbReport.downloadPublicMHBVersion?pOrgNr=14194&pStpStpNr=1970&pDocNr=14085952)

- [Software-Projektmanagement](https://online.rwth-aachen.de/RWTHonline/pl/ui/$ctx;design=pl;header=max;lang=de/wbModhbReport.downloadPublicMHBVersion?pOrgNr=14194&pStpStpNr=1975&pDocNr=14085970)

- [Projektmanagement](https://online.rwth-aachen.de/RWTHonline/pl/ui/$ctx;design=pl;header=max;lang=de/wbModhbReport.downloadPublicMHBVersion?pOrgNr=14194&pStpStpNr=1975&pDocNr=14085970)

- [Organizational Behavior & Human Resource Management](https://www.uni-potsdam.de/de/fop2/studium-und-lehre/bachelorveranstaltungen/organizational-behavior-und-hrm)

#### Recommended Course Literature

- [Remote Mob Programming](https://leanpub.com/remotemobprogramming)

- [Code with the Wisdom of the Crowd](https://pragprog.com/titles/mpmob/code-with-the-wisdom-of-the-crowd/)

- [Collaboration Explained](https://www.buecher.de/artikel/ebook/collaboration-explained-ebook-pdf/37826058/)

- [Team Topologies](https://www.thalia.de/shop/home/artikeldetails/A1053461194)

- [Technical Agile Coaching with the Samman method](https://leanpub.com/techagilecoach)

- [Lean Product and Process Development](https://www.abebooks.de/9781934109434/Lean-Product-Process-Development-Ward-1934109436/plp)

- [Extreme Programming Explained](https://www.pearson.de/extreme-programming-explained-embrace-change-9780134051994)

#### Programs

- [RWTH Informatik Bachelor](https://www.rwth-aachen.de/cms/root/studium/vor-dem-studium/studiengaenge/liste-aktuelle-studiengaenge/studiengangbeschreibung/~bnzs/informatik-b-sc-/)

- [RWTH Informatik Master](https://www.rwth-aachen.de/go/id/bcfg)

- [JMUW Informatik Master](https://www.informatik.uni-wuerzburg.de/studium/studiengaenge/master-informatik/)

::: {.content-visible when-format="html"}

::: {#refs}
:::

:::
