## RSEng, Ethics & Society
### Introduction

The RSE master's program is more than a computer science specialisation for researchers. People working as RSEs are often involved in digitalization projects, institutional development or other non-technical tasks. Also, introducing students to cutting-edge technologies, raises ethical questions. To talk about the impact of RSE on society, is therefore crucial. This module addresses the social context of RSEng. Students examine issues relating to sustainability, ethics, responsibility and the impact of new technologies. 
The module provides space for student-driven projects that address social challenges such as green tech and artificial intelligence, and encourages reflection on the role of RSEng in science and society.
It offers space for engagement with current challenges that are constantly changing but should be part of a curriculum in the age of digitalisation

### Contents
For a university level study program, it is fitting that students learn an abstract high-level understanding of their field so that they can adapt technical models, communication frameworks and policy recommendations to the complex cases. Therefor, they need a solid understanding in some of the more theoretical fields such as ...
- RSEng in the context of philosophy of science
- sociology of technology
- ethics and artificial intelligence
- human computer interaction
- digital humanities
- fundamentals and values of RSEng
- ethics and responsibility of (research) software engineers
- RSEng in the context of Open Science and the common good
- dual use dilemma
- sustainability and green technology
- future of work
- gender inequalities
- Technology assessment

### General Competences
This module conveys competences in areas such as but not limited to:
- discussion of ethical questions
- awareness of societal consequences
- conducting and leading research (NEW)
- understanding the research cycle (RC)

### Sources & Implementations:

#### Courses

- [Data Ethics Essentials](https://learning.theodi.org/courses/data-ethics-essentials)

- [Philosophische Grundlagen der Wissenschaften](https://www2.uni-wuerzburg.de/mhb/MHB1-de-B1-127-N-2015.pdf)

- [Einführung in die Wissenschaftstheorie](https://online.rwth-aachen.de/RWTHonline/pl/ui/$ctx;design=pl;header=max;lang=de/wbModhbReport.downloadPublicMHBVersion?pOrgNr=14194&pStpStpNr=1970&pDocNr=14085952)

- [Ethics, technology, and data](https://online.rwth-aachen.de/RWTHonline/pl/ui/$ctx;design=pl;header=max;lang=de/wbModhbReport.downloadPublicMHBVersion?pOrgNr=14194&pStpStpNr=1970&pDocNr=14085952)

- [Basismodul Grundlagen der Theoretischen Philosophie](https://www.uni-potsdam.de/de/studium/konkret/rechtsgrundlagen/studienordnungen/philosophie)

#### Teaching Resources

- [Responsible Computing (ethics teaching resources, assignments & publications)](https://www.internetruleslab.com/responsible-computing)

- [Green Algorithms (carbon-footprint calculators & sustainability training)](https://www.green-algorithms.org/)

#### Recommended Course Literature

- [Values in Science](https://www.lehmanns.de/shop/naturwissenschaften/58997490-9781009055635-values-in-science)

#### Programs

- [RWTH Informatik Bachelor](https://www.rwth-aachen.de/cms/root/studium/vor-dem-studium/studiengaenge/liste-aktuelle-studiengaenge/studiengangbeschreibung/~bnzs/informatik-b-sc-/)

::: {.content-visible when-format="html"}

::: {#refs}
:::

:::
