project:
  type: website
  output-dir: _site
  title: Showcase Curriculum for Research Software Engineering
  render:
    - "*.qmd"
    - "!presentation/"
    - "!thesis/"

website:
  title: "RSE Curriculum (WORK IN PROGRESS)"
  description: ""
  navbar:
    right:
      - text: "Workshops"
        href: event/kickoff-workshops/schedule.qmd
      - text: "Curriculum"
        href: generation/generated/curriculum.qmd
      - text: "Preambel"
        href: general/preambel_general.qmd
      - text: "ideas"
        href: general/ideas.qmd
      - text: "Job Roles"
        href: general/job_roles.qmd
      - text: "PDF-Version"
        href: _doc/RSE-Curriculum.pdf
      - text: "Glossary"
        href: general/glossary.qmd
      - text: "Repository"
        href: "https://github.com/the-teachingRSE-project/RSE-Masters/tree/tschira-funding"


format:
  html:
    theme: lux
    bibliography:
      - references.bib
      - external/bibliography/bibliography.bib

