sources:
  curricula:
    - name: EUMaster4HPC
      link: "https://eumaster4hpc.eu/studies/curriculum/"
  courses:
  programs:

  course_literature:
    - name: What every computer scientist should know about floating-point arithmetic
      link: "https://dl.acm.org/doi/10.1145/103162.103163"
