sources:
  curricula:
    - name: EUMaster4HPC
      link: "https://eumaster4hpc.eu/studies/curriculum/"
  courses:
    - name: Numerical Computing in Python
      link: "https://www.imperial.ac.uk/students/academic-support/graduate-school/professional-development/doctoral-students/research-computing-data-science/courses/numerical-computing-in-python-with-numpy--scipy/"
  programs:

  course_literature:
    - name: What every computer scientist should know about floating-point arithmetic
      link: "https://dl.acm.org/doi/10.1145/103162.103163"
