sources:
  curricula:
    - name: Computing Curricula 2020
      link: https://dl.acm.org/doi/book/10.1145/3467967
  courses:
    - name: Software Engineering I
      link: "https://puls.uni-potsdam.de/qisserver/pages/cs/sys/portal/hisinoneIframePage.faces?id=qis_MKSuchen_0&navigationPosition=up_modulbeschreibung%2Cqis_MKSuchen&recordRequest=true"
  programs:
    - name: UP Computational Science Master
      link: "https://www.uni-potsdam.de/de/studium/konkret/rechtsgrundlagen/studienordnungen/informatik"