# Objektive Hermeneutik
- formalisierte Interpretation
- Empfohlen als Gruppenauswertung
- Forschende betrachten den Text "unvoreingenommen" als in sich Schlüssiges ganzes
- sollen ggf. Vorwissen über den konkreten Text und seine Querbeziehungen zurückstellen
- Die Validität der Deutung ergibt sich nicht aus einer objektiven Quelle, sondern aus der nachvollziehbarkeit des Prozesses, Belegen und Ausschluss durch Falsifikation 


# 1. Schritt, Deutungshypothesen generieren
- Beginnt anhand eines Basisausschnitts aus dem Text, subjektiver Länge, und geht in Folgeschritten chronologisch vor
- Es sollen möglichst viele mögliche Deutungen "gedankenexperimentell" generiert werden
- D.h. es werden Vorkenntnisse über typische Gebrauchsweise der einzelnen Textelemente protokolliert (Inhalt, Stil)
- Dieser Schritt ist beendet, wenn keiner beteiligten Forschenden mehr weitere Interpretationen einfallen

# 2. Gruppierung und Auswahl
- Die generierten Deutungshypothesen werden thematisch geordnet
- Die Menge der Hinweise auf eine bestimmte Deutung, sowie der Ausschluss von falsifizierten Deutungen, ergeben die Auswahl

# 3. Überprüfung,  Verifikation an weiteren Belegstellen
- Die Deutungshypothesen werden anhand weiterer Textausschnitte entweder erweitert oder ausgeschlossen
- Auswahl möglicher Interpretationen wird weiter eingegrenzt und verfeinert

# 4. Einbezug von weiteren relevanten Theoriesätzen zur Auswertung
