sources:
  curricula:
    - name: 
      link: 
  courses:
    - name: Lecture Series on Research Methods
      link: "https://hpi.de/rabl/teaching/winter-term-2024-25/lecture-series-on-research-methods.html"
  programs:
    - name: 
      link: 
  course_literature:
    - name:
      link: 
