sources:
  curricula:
    - name:
      link: 
  courses:
    - name: "Formal Methods in Software Engineering"
      link: "https://www.uni-potsdam.de/fileadmin/projects/ambek/Amtliche_Bekanntmachungen/2024/Ausgabe_20/ambek-2024-20-885-891.pdf"
  programs:
    - name: UP Computational Science Master
      link: "https://www.uni-potsdam.de/de/studium/studienangebot/master/computational-science"
  course_literature:
    - name: 
      link: 
