sources:
  programs:

  courses:
    - name: Research methods & ethics
      link: "https://hpi.de/naumann/teaching/current-courses/ws-25-26/research-methods-methoden-der-forschung.html"
  course_literature:

