sources:
  courses:
    - name: Research Software Engineering
      link: "https://www.uni-potsdam.de/fileadmin/projects/ambek/Amtliche_Bekanntmachungen/2024/Ausgabe_20/ambek-2024-20-885-891.pdf"
    - name: Automated testing
      link: "https://coderefinery.github.io/testing/"
    - name: Documenting your research software
      link: "https://coderefinery.github.io/documentation/"
  programs:
    - name: UP Computational Science Master
      link: "https://www.uni-potsdam.de/de/studium/studienangebot/master/computational-science"
