sources:
  curricula:
    - name: 
      link: 
  courses:
    - name: Eingebettete Systeme
      link: "https://online.rwth-aachen.de/RWTHonline/pl/ui/$ctx;design=pl;header=max;lang=de/wbModhbReport.downloadPublicMHBVersion?pOrgNr=14194&pStpStpNr=1975&pDocNr=14085970"
    - name: Ausgewählte Kapitel der Embedded Systems
      link: "https://www2.uni-wuerzburg.de/mhb/MHB1-de-88-079-H-2025.pdf"
  programs:
    - name: RWTH Informatik Master
      link: "https://www.rwth-aachen.de/go/id/bcfg"
    - name: JMUW Informatik Master
      link: "https://www.informatik.uni-wuerzburg.de/studium/studiengaenge/master-informatik/"
  course_literature:
    - name: 
      link: "..."
