sources:
  curricula:
    - name: 
      link: 
  courses:
    - name: UP Sicherheit, Information und Komplexität
      link: "https://puls.uni-potsdam.de"
  programs:
    - name: UP Computational Science Master
      link: "https://www.uni-potsdam.de/de/studium/konkret/rechtsgrundlagen/studienordnungen/informatikcomputational-science"
    - name: JMUW Informatik Bachelor
      link: "https://www.informatik.uni-wuerzburg.de/studium/studiengaenge/bachelor-informatik/"
    - name: JMUW Informatik Master
      link: "https://www.informatik.uni-wuerzburg.de/studium/studiengaenge/master-informatik/"
  course_literature:
    - name: TODO
      link: "..."
